const ms = require('ms')
const Discord = require('discord.js')
const keySchema = require(`${process.cwd()}/modelos/clave.js`);
module.exports = {
    name: "keygen",
    aliases: ["generate-key", "generatekey"],
    desc: "Used to generate a Premium Key for a server",
    owner: true,
    run: async (client, message, args, prefix) => {
        if(!args.length) return message.reply(`❌ **You have to specify the Premium key duration!**\n**Example:** \`30d\``);
        const time = ms(args[0]) //convert user specified time to milliseconds
        if(time) {
            let key = generate_key();
            message.author.send({
                embeds: [new Discord.EmbedBuilder()
                .setTitle(`🔑 New Key!`)
                .setDescription("```"+key+"```")
                .addFields([
                    {name: "Generated by", value: `\`${message.author.tag}\` \`${message.author.id}\``},
                    {name: `Subscription`, value: `\`${args[0]}\``},
                    {name: `Status`, value: `\`UNUSED\``}
                ])
                .setColor(client.color)
                ]
            }).catch(() => {
                message.react("❌")
                return message.reply("❌ **I couldn't send you the DM with key details!\nKey deleted!**")
            });
            let data = new keySchema({
                clave: key,
                duracion: time,
                activado: false,
            });
            data.save();
            message.react("✅")
            return message.reply("✅ **New Key Generated in Database**\n*Key information has been sent to your DMs!*")
        } else {
            return message.reply("❌ **The Premium duration time you specified is not valid!**")
        }
    }
}

function generate_key(){
    //KEY: XXXX-XXXX-XXXX-XXXX
    let possibilities = "ABCDEFGHIJLKMNOPQRSTUVWXYZ0123456789";
    let part1 = "";
    let part2 = "";
    let part3 = "";
    let part4 = "";
    for(let i = 0; i < 4; i++){
        part1 += possibilities.charAt(Math.floor(Math.random() * possibilities.length));
        part2 += possibilities.charAt(Math.floor(Math.random() * possibilities.length));
        part3 += possibilities.charAt(Math.floor(Math.random() * possibilities.length));
        part4 += possibilities.charAt(Math.floor(Math.random() * possibilities.length));
    }
    //return generated key, e.g: ABJS-X252-GASH-6T1S
    return `${part1}-${part2}-${part3}-${part4}`
}

/*
╔═════════════════════════════════════════════════════╗
║    || - || Developed by awaiq310 || - ||           ║
╚═════════════════════════════════════════════════════╝
*/